version: '3'

services:
  db:
    restart: always
    container_name: crypto_jet_db
    image: postgres:13
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DATABASE_PORT}:5432
    command: postgres -c stats_temp_directory=/tmp    

  redis:
    image: redis:7
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  celery-worker:
    restart: always
    build: ./api
    command: celery -A background_tasks:celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  api:
    build: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    container_name: api
    env_file:
      - .env
    depends_on:
      - db, redis
  
  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
